#!/bin/bash
#skript väljastab inimeste arvu, tulemus on sama, kuigi kasutatakse 2 erineva konstruktsiooniga tsüklit
#10 inimese arvu väljastamine for tsükliga
for (( arv=1; arv<11; arv++ ))
do
	echo $arv
done
#skripti lõpp

echo ""
#10 inimese arvu väljastamine foreach tsükliga
for arv in {1..10}
do
	echo $arv
done
#skripti lõpp

#for tsükli näide - trükitakse "suvaline tegevus" nii palju korda, kui plaju on määratud
#"kord" muutujale, siis tsükkel lõpeb ära
for (( kord=1; kord<=5; kord++ ))
do
	echo "suvaline tegevus"
done
#skripti lõpp
