#!/bin/bash

#Paarisarvude arvutamine FOR abil

summa=0
#echo "summa: $summa"
for (( arv=1; arv<11; arv++ ))
do
	jaak=$(($arv %2))
	if [ $jaak -eq 0 ];then
		summa=$(($summa + $arv))
		echo $summa
	fi
done
echo "Arvude vahemikus 1 kuni 10 (kaasaarvutud) paarisarvude summa on: $summa"
