#!/bin/bash

#CASE kösu kasutamine (kasutaja sisestab kuu number ning skript völjastab kuu nimetuse)

echo -n "Palun sisestage kuu number (1-12): "
read num

if [ $num -eq 0 -o $num -ge 13 ]; then
	echo "Palun sisestage ainult õiged numbrid!!! (vahemikus 1-12)"
else
	#Kriteeriumite vaatamine listist
	case $num in
		"1") echo "Jaanuar";;
		"2") echo "Veebruar";;
		"3") echo "Märts";;
		"4") echo "Aprill";;
		"5") echo "Mai";;
		"6") echo "Juuni";;
		"7") echo "Juuli";;
		"8") echo "August";;
		"9") echo "September";;
		"10") echo "Oktoober";;
		"11") echo "November";;
		"12") echo "Detsember";;
	esac
fi

