#!/bin/bash
#testimis skript tsüklite kasutamisest


for (( i = 1; i <= 5; i++ ))      ### Outer for loop ###
do
    for (( j = 1 ; j <= 5; j++ )) ### Inner for loop ###
    do
	#väljastada i ilma reavahetuseta
          echo -n "$i "
    done
  echo "" #### print the new line ###
done
