#!/bin/bash
#skript peab küsima kasutajalt mitu rida tuleb sisestada ja mitu * reas peab olema

echo -n "Sisestage ridade arv: "
read rida
echo -n "Sisestage tärnide arv reas: "
read tarn

for (( i = 1; i <= $rida; i++ ))      ### Outer for loop ###
do
	#nüüd väljastame number rea ette
	echo -n "$i. "
	for (( j = 1 ; j <= $tarn; j++ )) ### Inner for loop ###
	do
	   	echo -n "* "
    	done
  	echo "" #### print the new line ###
done
