#!/bin/bash
#This is a comment

echo -n "Sisestage inimeste arvu: "
read iarv
echo -n "Sisestage mitu kohti bussis: "
read bus
#arvutame mitu bussi on vaja
yle=$(($iarv % $bus))
#arvutame mitu inimest jääb üle
group=$(($iarv / $bus))
#kui on olemas ülejaanud, tuleb suurendada busside arv ühe võrra
if test $group -gt 0
then
	#"group" muutuja vajab üledefineerimist, selle pärast ümber salvestamiseks ei kasuta "$" marki
	group=$(($group +1))
fi
#tulemuste väljastamine
echo "Inimse, kes jääb üle: $yle"
echo "Bussi on kokku vaja: $group"
